### ISSUE TITLE
Déploiement local pour test

### ISSUE THREAD

**Issue by ColinMaudry** [cartesapp/cartes#710]
Je souhaite ajouter une fonctionnalité révolutionnaire à cartes.app: la possibilité de rajouter cartes.app aux moteurs de recherche du navigateur en un clic. Pour tester cette killer feature, j'ai besoin de déployer cartes.app en local.

Les [instruction de contributions](https://github.com/cartesapp/cartes/blob/master/CONTRIBUTING.md) indiquent qu'avec node installé (j'ai pris la dernière version, 18) et NPM, il suffit de lancer la commande suivante:

```
npm run dev --legacy-peer-deps
```

Malheureusement j'ai cette erreur:

```
> $ npm run dev --legacy-peer-deps

> cartes@0.4.0 dev
> next dev -p 8080

node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'next-contentlayer2' imported from /home/colin/git/cartes_test/next.config.mjs
    at new NodeError (node:internal/errors:405:5)
    at packageResolve (node:internal/modules/esm/resolve:916:9)
    at moduleResolve (node:internal/modules/esm/resolve:973:20)
    at defaultResolve (node:internal/modules/esm/resolve:1206:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:404:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:373:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:250:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:39)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v18.20.5
```

Je tente un traditionnel `npm install --legacy-peer-deps` préliminaire, mais `npm run dev --legacy-peer-deps ` renvoie une nouvelle erreur:

```
> cartes@0.4.0 dev
> next dev -p 8080

   ▲ Next.js 15.0.3
   - Local:        http://localhost:8080
   - Environments: .env.development, .env
   - Experiments (use with caution):
     · turbo
     · reactCompiler

 ✓ Starting...
   automatically enabled Fast Refresh for 1 custom loader
Contentlayer config change detected. Updating type definitions and data...
This error shouldn't have happened. Please consider opening a GitHub issue with the stack trace below here:
https://github.com/timlrx/contentlayer2/issues

An unchecked error was produced.

TypeError: Cannot read properties of undefined (reading 'cwd')
    at f (file:///home/colin/git/cartes_test/node_modules/@contentlayer2/core/src/cwd.ts:24:53)
    at f (file:///home/colin/git/cartes_test/node_modules/@effect-ts/system/_src/Effect/has.ts:121:43)
    at IRead.f (file:///home/colin/git/cartes_test/node_modules/@effect-ts/system/_src/Effect/has.ts:113:33)
    at FiberContext.evaluateNow (file:///home/colin/git/cartes_test/node_modules/@effect-ts/system/_src/Fiber/context.ts:1136:31)
    at file:///home/colin/git/cartes_test/node_modules/@effect-ts/system/_src/Fiber/context.ts:576:33
    at file:///home/colin/git/cartes_test/node_modules/@effect-ts/system/_src/Support/Scheduler/index.ts:15:9

Fiber: #34 (started at: 2024-12-05T14:07:28.098Z) was supposed to continue to: <empty trace>
Fiber: #34 (started at: 2024-12-05T14:07:28.098Z) Execution trace: <empty trace>
Fiber: #34 (started at: 2024-12-05T14:07:28.098Z) was spawned by:
Fiber: #32 (started at: 2024-12-05T14:07:28.097Z) was supposed to continue to: <empty trace>
Fiber: #32 (started at: 2024-12-05T14:07:28.097Z) Execution trace: <empty trace>
Fiber: #32 (started at: 2024-12-05T14:07:28.097Z) was spawned by:
Fiber: #26 (started at: 2024-12-05T14:07:28.090Z) was supposed to continue to: <empty trace>
Fiber: #26 (started at: 2024-12-05T14:07:28.090Z) Execution trace: <empty trace>
Fiber: #26 (started at: 2024-12-05T14:07:28.090Z) was spawned by:
Fiber: #5 (started at: 2024-12-05T14:07:27.921Z) was supposed to continue to: <empty trace>
Fiber: #5 (started at: 2024-12-05T14:07:27.921Z) Execution trace: <empty trace>
Fiber: #5 (started at: 2024-12-05T14:07:27.921Z) was spawned by:
Fiber: #0 (started at: 2024-12-05T14:07:27.908Z) was supposed to continue to: <empty trace>
Fiber: #0 (started at: 2024-12-05T14:07:27.908Z) Execution trace: <empty trace>
Fiber: #0 (started at: 2024-12-05T14:07:27.908Z) was spawned by: <empty trace>

OS: linux 6.8.0-49-generic (arch: x64)
Process: /home/colin/.nvm/versions/node/v18.20.5/bin/node /home/colin/git/cartes_test/node_modules/next/dist/server/lib/start-server.js
Node version: v18.20.5
Contentlayer version: 0.5.1
```
Je suis sous Ubuntu 24.04.

**Comment by ColinMaudry** [comment]
J'ai essayé avec les instructions du README:

```
bun install
bun dev
```

J'install bun:

```
npm i bun -g
```

J'ai cette erreur suite à la commande`bun dev` :

```
$ next dev -p 8080
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '/home/colin/git/cartes_test/node_modules/mdast-util-gfm-autolink-literal/node_modules/mdast-util-find-and-replace/' imported from /home/colin/git/cartes_test/node_modules/mdast-util-gfm-autolink-literal/lib/index.js
Did you mean to import mdast-util-find-and-replace/index.js?
    at new NodeError (node:internal/errors:405:5)
    at legacyMainResolve (node:internal/modules/esm/resolve:218:9)
    at packageResolve (node:internal/modules/esm/resolve:903:14)
    at moduleResolve (node:internal/modules/esm/resolve:973:20)
    at defaultResolve (node:internal/modules/esm/resolve:1206:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:404:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:373:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:250:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:39)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v18.20.5
error: script "dev" exited with code 1
```

**Comment by ColinMaudry** [comment]
Le code bash de déploiement utilisé par vercel est pas dans le repo ?

**Comment by laem** [comment]
Mmh, ton erreur est étrange, car en clonant dans un nouveau dépôt ça marche du premier coup pour moi avec `bun install && bun run dev`. 

Je vois que tu utilises node 18, c'est une vieille version et surtout Bun remplace node, donc ta commande a visiblement été lancée avec node. 

Je ne pense pas qu'installer bun via node soit recommandé, plutôt via ça https://bun.sh/docs/installation.

**Comment by ColinMaudry** [comment]
C'est bon !
